server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_test?serverTimezone=GMT
    username: root
    password: 123456

logging:
  level:
    com.zimug.bootlaunch: debug


family:
  family-name: bad family
  father:
    name: lao wang
    age: 30
  mother:
    alias:
      - lovely
      - ailice
  child:
    name: Xiao Tou
    age: 9
    friends:
      - hobby: football
        sex:  male
      - hobby: basketball
        sex: female

