server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_test?serverTimezone=GMT
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

family:
  family-name: bad family
  father:
    name: lao wang
    age: 30
  mother:
    alias:
      - lovely
      - ailice
  child:
    name: Xiao Tou
    age: 9
    friends:
      - hobby: football
        sex:  male
      - hobby: basketball
        sex: female

